### ISSUE TITLE
`vue/padding-line-between-tags` moet weg

### ISSUE THREAD

**Issue by YouriLieverdink** [script-development/eslint-config-base#3]

**Comment by YouriLieverdink** [comment]
@QGIsK , hoe staat dit ervoor? 😂

**Comment by Goosterhof** [comment]
@YouriLieverdink waarom moet dit er uit? Maakt de templates toch wat overzichtelijker allemaal? Of moet er iets worden aangepast binnen de regel?

**Comment by YouriLieverdink** [comment]
@Goosterhof , omdat dingen zoals hieronder dan ook worden geforceerd. Terwijl dat niet echt nodig is vind ik.

```html
<thead>
    <tr>
        <td>Uitbetalingsdatum</td>

        <td>Leeftijd jongste contractpartner</td>

        <td>Uw schuld</td>

        <td>Rentebijschrijving {{ interestRate }}%</td>

        <td>Te ontvangen</td>
    </tr>
</thead>
```

**Comment by Goosterhof** [comment]
Daarvoor idd niet per se nodig. Maar ik vind het met hele grote templates wel prettig. Misschien dat er wat options zijn bij die regel die we kunnen gebruiken. Zal daar eens naar kijken zodra ik tijd heb
